version: "3.4"

services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - techbankNet

  mysqldb:
    image: mysql
    container_name: mysqldb
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=techbankRootPsw
    volumes:
      - mysql_data_container:/var/lib/mysql
    networks:
      - techbankNet

  postgresdb:
    image: postgres
    container_name: postgresdb
    environment:
      - POSTGRES_USER=admin    
      - POSTGRES_PASSWORD=techbankRootPsw
      - POSTGRES_DB=bankAccount    
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_container:/var/lib/postgresql/data/  
    networks:
      - techbankNet

  zookeeper:
    container_name: zookeeper
    image: bitnami/zookeeper
    restart: always
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - techbankNet

  kafka:
    container_name: kafka
    image: bitnami/kafka
    ports:
      - "9092:9092"
    restart: always
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    depends_on:
      - zookeeper
    networks:
      - techbankNet

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  mongodb_data_container:
  mysql_data_container:
  postgres_data_container:


networks:
  techbankNet:
    name: techbankNet
    driver: bridge

# networks:
#   default:
#     external:
#       name: techbankNet
